# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMessageAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=20)),
                ('ts', models.CharField(max_length=50)),
                ('channel_id', models.CharField(max_length=40)),
                ('message_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveMessageResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('ts', models.CharField(max_length=50)),
                ('message_text', models.TextField()),
                ('leave_messake_ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.LeaveMessageAsk')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=15)),
                ('team_name', models.CharField(max_length=150)),
                ('bot_user_id', models.CharField(max_length=15)),
                ('bot_access_token', models.CharField(max_length=150)),
                ('user_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='leavemessageask',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.WorkSpace'),
        ),
    ]
