# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMessageAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=20)),
                ('ts', models.CharField(max_length=50)),
                ('channel_id', models.CharField(max_length=40)),
                ('message_text', models.TextField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.WorkSpace')),
            ],
        ),
    ]
