# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='announcing_channel_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='announcing_channel_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
