# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_leavemessageask'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMessageResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('ts', models.CharField(max_length=50)),
                ('message_text', models.TextField()),
                ('leave_messake_ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.LeaveMessageAsk')),
            ],
        ),
    ]
