# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_auto_20171202_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='team_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
