# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botapp', '0002_remove_workspace_announcing_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='moderators',
            field=models.ManyToManyField(null=True, related_name='moders', to=settings.AUTH_USER_MODEL),
        ),
    ]
